# TODO: complete these lists

GENERAL_KEYWORDS = ['DATE', ' TIME', 'END']

SIMULATION_KEYWORDS = ['MODE', 'ISOTHERMAL', 'NOSLVSOL', 'NOGASSOL', 'RESERVOIR_DEFAULTS', 'ANALYTICAL_JACOBIAN',
                       'HYSTERESIS', 'HYSTERESIS_PC', 'EHYST', 'RESTART', 'ERESTART', 'CHECKPOINT', 'TL_OMEGA', 
                       'COMP_DEP_SFNS', 'STRAND', 'ABOUT', 'PREAMBLE', 'FLOWS', 'SATDEN', 'OPTIONS', 'MISCIBLE',
                       'LOCAL_DIAGONAL_TENSOR']

WELLS_KEYWORDS = ['WELL_TYPE', 'OPEN', 'SHUT', 'RADIUS', 'DIAMETER', 'USE_HIST_TARG', 'CIJK_D', 'CIJKL_D', 'SKIN_FACTOR', 
                  'EFFECTIVE_KH', 'PRESSURE_RADIUS_R0', 'CONST_DRILL_DIR', 'BHPL', 'D_REF', 'Z_REF', 'INJECTION_ENTHALPY_P', 
                  'INJECTION_ENTHALPY_T', 'ZINJ', 'MULTI_PI', 'GC_WEIGHT']

AQUIFER_KEYWORDS = ['BACKFLOW', 'DEPTH', 'ZAQUIFER', 'THETA_FRACTION', 'THETA', 'THICKNESS', 'WIDTH', 'RADIUS', 
                    'PERM', 'PERMEABILITY', 'CMPR', 'COMPRESSIBILITY', 'PORO', 'POROSITY', 'VISC', 'VISCOSITY', 
                    'PINIT', 'PRESSURE', 'TINIT', 'TEMPERATURE', 'GAS_IN_LIQUID_MOLE_FRACTION', 'IFT', 
                    'CONN_D', 'CONN_Z', 'FET', 'PV', 'PI']

EQUILIBRATION_KEYWORDS = ['DATUM_D', 'PRESSURE', 'WGC_D', 'PCWG_WGC', 'OWC_D', 'PCOW_OWC', 'OGC_D', 'PCOG_OGC',
                          'BUBBLE_POINT_TABLE', 'RTEMP', 'TEMPERATURE_TABLE', 'SALT_TABLE', 'GAS_IN_LIQUID_MOLE_FRACTION',
                          'SOLVENT_IN_LIQUID_MOLE_FRACTION', 'ZMFVD', 'NUM_EQUIL_NODES']

OPENGOSIM_KEYWORDS = GENERAL_KEYWORDS + WELLS_KEYWORDS
