# TODO: complete these lists

GENERAL_KEYWORDS = ['DATE', ' TIME', 'END']

WELLS_KEYWORDS = ['OPEN', 'SHUT', 'RADIUS', 'DIAMETER', 'SKIN_FACTOR', 'EFFECTIVE_KH', 'PRESSURE_RADIUS_R0',
                  'CONST_DRILL_DIR']

AQUIFER_KEYWORDS = ['BACKFLOW', 'DEPTH', 'THICKNESS', 'RADIUS', 'PERM', 'COMPRESSIBILITY', 'POROSITY',
                  'VISCOSITY', 'CONN_D']

OPENGOSIM_KEYWORDS = GENERAL_KEYWORDS + WELLS_KEYWORDS
